### ISSUE TITLE
Custom libp2p for browser based js-ipfs node (private network - swarmkey)

### ISSUE THREAD

**Issue by bigjpr83** [libp2p/js-libp2p-pnet#3]
How can js-libptp-pnet be used to connect to a private network using a swarm.key? Any examples?

**Comment by jacobheun** [comment]
We do need to get an example published. 

You can pass a libp2p-pnet instance to a libp2p node when configuring it. This assumes you have used the readme here to create a swarm.key file.
```js
const Libp2p = require('libp2p')
const Protector = require('libp2p-pnet')
const swarmKeyBuffer = /* Return a buffer of your key, such as via fs.readFileSync */

const libp2pNode = new Libp2p({
  ...
  modules: {
    connProtector: new Protector(swarmKeyBuffer)
  }
})
```

When the connProtector is provided `libp2p-switch` will automatically privatize all connections.

**Comment by gitGksgk** [comment]
@jacobheun 

I've followed this instruction adding protect to js-ipfs but got an error : "protect is required"
```
   "connProtector": {
      "psk": {
        "type": "Buffer",
        "data": [
          117, 120, 85, 0, 16, 105, 109, 154, 52, 13, 254, 5, 21, 37, 10, 93, 188, 91, 91, 19, 178, 111, 16, 27, 49, 24, 240, 197, 14, 67, 52, 87
        ]
      },
      "tag": "/key/swarm/psk/1.0.0/",
      "protect" [1]: -- missing --
    }
```
I tried to define protect as '/base16/' and i got
```
[1] "protect" must be a Function
    at Object.exports.process (environment\js-ipfs\node_modules\joi\lib\errors.js:196:19)
    at internals.Object._validateWithOptions (environment\js-ipfs\node_modules\joi\lib\types\any\index.js:675:31)
    at module.exports.internals.Any.root.validate (environment\js-ipfs\node_modules\joi\lib\index.js:138:23)
    at module.exports.internals.Any.root.attempt (environment\js-ipfs\node_modules\joi\lib\index.js:167:29)
    at module.exports.validate (environment\js-ipfs\node_modules\libp2p\src\config.js:42:17)
    at new Node (environment\js-ipfs\node_modules\libp2p\src\index.js:32:16)
    at new Node (environment\js-ipfs\src\core\runtime\libp2p-nodejs.js:60:5)
    at gotConfig (environment\js-ipfs\src\core\components\libp2p.js:61:28)
    at store.get (environment\js-ipfs\node_modules\ipfs-repo\src\config.js:45:9)
    at environment\js-ipfs\node_modules\graceful-fs\graceful-fs.js:78:16
```
got no idea of what protect should be. Why doesn't  new Protector(swarmKeyBuffer) produce everything we need?

**Comment by gitGksgk** [comment]
related code:
in httpapi 

const Protector = require('libp2p-pnet')
const keypath = path.join(os.homedir(), '.jsipfs', 'swarm.key')
const protector = new Protector(fs.readFileSync(keypath))
libp2p.modules.connProtector = protector

**Comment by gitGksgk** [comment]
okay I've figured it out..

**Comment by jacobheun** [comment]
@gitGksgk sorry for the delay, I was traveling this weekend. I went ahead and put together an example that runs some IPFS nodes, #4. The `libp2p-bundle` code could be re-used for pure libp2p nodes as well.  Let me know if that helps clarify things and/or if there is anything in the example that's not clear. Feedback on that would be appreciated!

**Comment by gitGksgk** [comment]
@jacobheun  thanks for your reply. haven't tested the example, I notice that in 
```
return new Libp2p({
      peerInfo,
      peerBook,
      modules: {
        transport: [ TCP ], // We're only using the TCP transport for this example
        streamMuxer: [ MPLEX ], // We're only using mplex muxing
        // Let's make sure to use identifying crypto in our pnet since the protector doesn't
        // care about node identity, and only the presence of private keys
        connEncryption: [ SECIO ],
        // Leave peer discovery empty, we don't want to find peers. We could omit the property, but it's
        // being left in for explicit readability.
        // We should explicitly dial pnet peers, or use a custom discovery service for finding nodes in our pnet
        peerDiscovery: [ ],
        connProtector: new Protector(fs.readFileSync(swarmKeyPath))
      }
    })
  }
```
there's still no key 'protect'. not sure if it will encounter the same error. The error was quite strange though. I have to set 
```
   libp2p.modules.connProtector = protector
   libp2p.modules.connProtector.protect = protector.protect
```
to make it work because of some sort of Joi assertion. 
Here I got another question.  will js-ipfs option: peer discovery conflict with libp2p-bundle's peer discovery setting?

**Comment by jacobheun** [comment]
Joi is complaining that the `.protect` method is missing on the protector, which is required to wrap the base connection and privatize it. Everything should be passed by configuration to the libp2p constructor. Setting ` libp2p.modules.connProtector` directly isn't supported.

In regards to **peer discovery**, yes doing custom configuration of the libp2p node as shown in the example will change the ipfs behavior. If you want to mimic how ipfs is setup you can take a look at default configuration in the node at https://github.com/ipfs/js-ipfs/blob/master/src/core/runtime/libp2p-nodejs.js.  A note, with private networks you likely aren't going to want to run peer discovery, which is why it's empty in the example. Unless you are doing custom discovery to find other nodes in your private network.

**Comment by gitGksgk** [comment]
awesome. Just one more question. Why is it that with private networks we don't want to run peer discovery? Currently I need to discover other nodes in the same private network. Did you mean that the functionality will behave unexpectedly like exposing private node to the public?

**Comment by jacobheun** [comment]
If you have your own bootstrap nodes on your private network that new nodes dial to for running peer-discovery then that's totally fine, you'll just want to avoid dialing out to public networks. The nodes won't connect but you may hit some unwanted side effects waiting to connect.

**Comment by gitGksgk** [comment]
@jacobheun  okay I see. Many thanks!
