### ISSUE TITLE
Use within js-ipfs

### ISSUE THREAD

**Issue by gaillard** [libp2p/js-libp2p-pnet#6]
If the usage shown in https://github.com/ipfs/js-ipfs/issues/1857 correct?

I have a suspicion it is because of the private network that it is having trouble.

**Comment by jacobheun** [comment]
It looks like the issue was solved in ipfs/js-ipfs#1857. Feel free to open if you're having issues. Apologies for the slow reply, I was apparently not watching the repo, which I fixed.
